package com.signalchain.app.ml
import ai.onnxruntime.*;import android.content.Context;import com.signalchain.app.dsp.Fft;import kotlin.math.*
class OnnxDenoiser(context:Context,assetPath:String="models/spectral_mask_denoiser.onnx"):AutoCloseable{
 private val env=OrtEnvironment.getEnvironment();private val session=env.createSession(context.assets.open(assetPath).readBytes())
 private fun resampleLinear(x:FloatArray,srcRate:Int,dstRate:Int):FloatArray{if(srcRate==dstRate)return x;require(srcRate>0&&dstRate>0);val ratio=dstRate.toDouble()/srcRate.toDouble();val outLen=max(1,(x.size*ratio).toInt());return FloatArray(outLen){i->val srcPos=i/ratio;val i0=srcPos.toInt().coerceIn(0,x.size-1);val i1=(i0+1).coerceIn(0,x.size-1);val frac=(srcPos-i0).toFloat();x[i0]*(1-frac)+x[i1]*frac}}
 private fun reflectPad(x:FloatArray,pad:Int):FloatArray{val n=x.size;require(n>pad){"Audio too short for centered STFT (need > $pad samples, got $n)"};return FloatArray(n+2*pad){i->when{ i<pad->x[pad-i];i>=pad+n->x[n-2-(i-pad-n)];else->x[i-pad] }}}
 private fun stftCentered(x:FloatArray,nFft:Int,hop:Int)=Fft.stft(reflectPad(x,nFft/2),nFft,hop)
 private fun istftCentered(s:Array<Array<Pair<Float,Float>>>,hop:Int,nFft:Int,originalLen:Int):FloatArray{val padded=Fft.istft(s,hop);val start=nFft/2;val end=(start+originalLen).coerceAtMost(padded.size);return padded.copyOfRange(start,end).let{if(it.size<originalLen)it+FloatArray(originalLen-it.size)else it}}
 fun predictMask(x:Array<FloatArray>):Array<FloatArray>{val f=x.size;val t=x[0].size;val input:Array<Array<Array<FloatArray>>> = Array(1){Array(1){Array(f){FloatArray(t)}}};for(i in 0 until f)input[0][0][i]=x[i];OnnxTensor.createTensor(env,input).use{tensor->session.run(mapOf("features" to tensor)).use{r->@Suppress("UNCHECKED_CAST")return (r[0].value as Array<Array<Array<FloatArray>>>)[0][0]}}}
 fun apply(audio:FloatArray,sampleRate:Int):FloatArray{val resampled=resampleLinear(audio,sampleRate,16000);val s=stftCentered(resampled,512,128);val mag=Array(s[0].size){k->FloatArray(s.size){j->ln(1+sqrt(s[j][k].first*s[j][k].first+s[j][k].second*s[j][k].second))}};val mask=predictMask(mag);val out=Array(s.size){j->Array(s[j].size){k -> val m=mask[k][j];s[j][k].first*m to s[j][k].second*m}};val denoised16k=istftCentered(out,128,512,resampled.size);return resampleLinear(denoised16k,16000,sampleRate)}
 override fun close(){session.close();env.close()}
}
